version: '3.8'

services:
  praetor-backend:
    build: .
    container_name: praetor-backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./honeypot.db
      - LOG_DIR=logs/
    env_file:
      - .env
    restart: unless-stopped
